language: go
go:
  - 1.8
sudo: required
services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t innovate/dispatch ./
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push innovate/dispatch; fi