language: go
go:
- 1.9
install:
- go get -d -v ./...
- go vet ./...
- travis_wait go test ./... -timeout 20m
#- ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cd dispatchd && go build -v ./ && mv dispatchd dispatchd-linux-amd64 && cd ..
  - cd dispatchd && GOARCH=arm go build -v ./ && mv dispatchd dispatchd-linux-arm && cd ..
  - cd dispatchd && GOARCH=arm64 go build -v ./ && mv dispatchd dispatchd-linux-arm64 && cd ..
  - cd dispatchctl && go build -v ./ && mv dispatchctl dispatchctl-linux-amd64 && cd ..
  - cd dispatchctl && GOARCH=arm go build -v ./ && mv dispatchctl dispatchctl-linux-arm && cd ..
  - cd dispatchctl && GOARCH=arm64 go build -v ./ && mv dispatchctl dispatchctl-linux-arm64 && cd ..

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Odwt4DwCsB4TZJyi5Z4X1r8gCWAWoLoq7l2zAtXBU5uMpc9PpL3RHYL7J0aeiGg0zaBdWjI09Rsrz1VKrDPw+DfWZr4kisKIJCd1Aag2/IItMFPWRrU703iavCGns/RUoryf3K0Rlt7GX6d+Dx9Aifyq8FGsGsPDsLTRtr7PO5l7/VBb+4YvNpLFPsHrTMYig2nvGAxE2oG0XVSTuoM2f4/D5i6VlusZZnAGZcuvxJgI8xefr2caUIm7ikJB7jb3aKeeVppe4oHaZY2YLbTSuzclkpqTsBjI8kwYWqdHyhgNUp+ylVngXlGevvC4GyaJe/iuvgal1Fde/57701qE2k3Cj4IZdGrzuHX8BWuugvuq0+WzpIFiEHZuvo85sRSg4VNT8v6Z1sSiNtfi+RkGWPowEXnOf2mvfJkBJNygOOKG3ugK0sEpo4cV9tiSZsWtYkHNljaxBSMHdIMk+m1vPwsAPnufbmb2JArlAeIq9XZ9tuTjvDWYUT2ecTFFaT5CnrkV9xIBQnX/MKCiaPwfLnSvPEMqUdM8o0leVje7NrU2Uob7xWKctvjARIfgYWCWw1k/u9SXcqDCoD2ttA7poM8lUmjGI0LYrnnD9q31h3w1pNrW+eeGlIBQcUghF023lKo8aPowameMV+MvgajQb0QX+Nw8N0mTSnPoNT1OxSI=
  file: 
    - dispatchd/dispatchd-linux-amd64
    - dispatchd/dispatchd-linux-arm 
    - dispatchd/dispatchd-linux-arm64
    - dispatchctl/dispatchctl-linux-amd64
    - dispatchctl/dispatchctl-linux-arm
    - dispatchctl/dispatchctl-linux-arm64
  overwrite: true
  on:
    repo: innovate-technologies/Dispatch
    branch: "master"
    tags: true
