version: '2'
services:
  node1:
    build: ./node
    links:
      - etcd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  node2:
    build: ./node
    links:
      - etcd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  etcd:
    image: maartje/etcd-multiarch:amd64-v3.2.7
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379